### ISSUE TITLE
Cellular crashes if survive is supplied

### ISSUE THREAD

**Issue by globalcitizen** [paulofmandown/rotLove#12]
I am trying to develop a roguelike to release for [2016 ARRP](http://www.roguebasin.com/index.php?title=2016_ARRP). You can have a look at it on [Roguebasin](http://www.roguebasin.com/index.php?title=Zomia) or [Github](https://github.com/globalcitizen/zomia). It's coming together pretty well!

Unfortunately I have run in to another issue, again with Cellular, and I do need it because I am attempting to port the entire physical dungeon generation algorithm from [Brogue](https://sites.google.com/site/broguegame/).

Unfortunately I only have a few days left, so I am hoping you will have time to help out again 👍 

The function source... 
```
function ROT.Map.Cellular:create(callback)
    local newMap =self:_fillMap(0)
    local born   =self._options.born
    local survive=self._options.survive
    local changed=false

    for j=1,self._height do
        for i=1,self._width do
            local cur   =self._map[i][j]
            local ncount=self:_getNeighbors(i, j)
            if cur>0 and table.indexOf(survive, ncount)>0 then
                newMap[i][j]=1
```

Crashes with:
```
Error: rotLove.lua:104: attempt to get length of local 'values' (a number value)
stack traceback:
       	rotLove.lua:104: in function 'indexOf'
       	rotLove.lua:1944: in function 'create'
```

rotLove.lua:1944 is:
```
            if cur>0 and table.indexOf(survive, ncount)>0 then
```

I am calling it like:
```
        cl = ROT.Map.Cellular:new(minwidth,maxwidth,{topology=8,minimumZoneArea=math.max(minheight,minwidth),survive=4})
        cl:randomize(.50)
        cl:create(my_callback_helper)
```

**Comment by paulofmandown** [comment]
survive has to be a table of ints
Try something more like this:
```lua
cl = ROT.Map.Cellular:new(
        minwidth,
        maxwidth,
        {
          topology=8,
          minimumZoneArea=math.max(minheight,minwidth),
          survive={4}
        }
)
```

**Comment by globalcitizen** [comment]
Thanks 👍  ... I read the docs but totally missed that. Lack of sleep I suppose.

**Comment by globalcitizen** [comment]
Verified that works.
