### ISSUE TITLE
Bugfix in dice module required

### ISSUE THREAD

**Issue by timothymtorres** [paulofmandown/rotLove#18]
After doing some testing today when I was adding a new feature I came across a severe bug that affects older versions of RL-Dice (including the rotLove dice module).  The bug is triggered whenever the user is using sets, and causes the dice bonus to be the number of dice due to a pattern matching loophole I missed.  Luckily a small fix is all that is required!

The following lines of code on lines 5661, 5662 at [rotLove.lua](https://github.com/paulofmandown/rotLove/blob/master/rotLove/rotLove.lua) need to be changed from:

	local double_bonus = string.match(dice_notation, '[^%^+-]([+-]?[+-])%d+')
	local bonus = string.match(dice_notation, '[^%^+-][+-]?([+-]%d+)')

to the following:

	local double_bonus = string.match(dice_notation, '[d]%d+([+-]?[+-])%d+')
	local bonus = string.match(dice_notation, '[d]%d+[+-]?([+-]%d+)')

And it should be good to go!

**Comment by buckle2000** [comment]
Also in `dice_basic.lua`:
you used `D&D-xxxx` as a variable name.

**Comment by timothymtorres** [comment]
@buckle2000   I noticed that earlier but didn't think it warranted a issue request because it was apart of the examples.  A better variable name would have been `DnD-xxxx`.
