### ISSUE TITLE
Dice function results in identical rolls if given identical parameters

### ISSUE THREAD

**Issue by Zireael07** [paulofmandown/rotLove#19]
`for i=1,6 do
        self.rolled[i] = ROT.Dice.roll('3d6')
    end`

results in six identical rolls (e.g. six tens or six eights) instead of six different 3d6 rolls (e.g. 8, 9, 10, 12, 8, 13)

**Comment by timothymtorres** [comment]
I'll take a look at this later tonight.  It may be that the ROT.Dice.roll isn't properly creating a new dice instance when utilized a certain way.
