### ISSUE TITLE
ROT.DijkstraMap issues

### ISSUE THREAD

**Issue by Rakaneth** [paulofmandown/rotLove#43]
There is a call to write(s) in ROT.DijkstraMap:writeMapToConsole; this function is not defined anywhere.

**Comment by airstruck** [comment]
There are also references to that `write` function in Corridor, Room, and BrogueRoom; they fall back to `io.write`.

DijkstraMap and Rogue attempt to call it directly and don't fall back to `io.write`.

This is probably supposed to be the `write` function from newFuncs.lua; I made it local to that file a while back, thinking it was just global to get a "hoisting" effect and not realizing it was used in other files.

Solution could be defining something like `ROT.log` and using that instead.

**Comment by paulofmandown** [comment]
I like those ideas. For now, though, I'm going to remove write to get rid of the error

Addressed in 3f240b21920a2f230a0936c11116cd64462f7538
