### ISSUE TITLE
Demos/examples outdated and errors

### ISSUE THREAD

**Issue by Zireael07** [paulofmandown/rotLove#7]
I tried Djikstra map demo and then Djikstra map example. The demo errored out, the example from master worked only after I manually fixed the path to 30log.

The display example in master doesn't work at all, freezes Love.

**Comment by Zireael07** [comment]
icey maze and eller maze demos don't run either. One has the same problem as djikstra map (foreground color), the other complains about rng

**Comment by paulofmandown** [comment]
Hey I was able to get most of it working again over my lunch break. Update here if find anything else going wrong. The engine demo is for sure still not working, though.

**Comment by Zireael07** [comment]
Thanks mate, appreciate you still being interested in this having started so long ago :heart:

**Comment by globalcitizen** [comment]
They all worked for me.
