### ISSUE TITLE
Bug in connected mode for cellular map type

### ISSUE THREAD

**Issue by globalcitizen** [paulofmandown/rotLove#9]
Runs OK (but rooms are not connected, so very un-dungeonlike and sorta useless!).

`cl=ROT.Map.Cellular:new(resolutionTilesX, resolutionTilesY)`

Crashes every time.

`cl=ROT.Map.Cellular:new(resolutionTilesX, resolutionTilesY, {connected=true})`

**Comment by paulofmandown** [comment]
This should be fixed with a1f3f2f.
